# Generated by Django 4.0.2 on 2022-02-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='updated_ar',
            new_name='updated_at',
        ),
    ]
